# Generated by Django 2.0 on 2019-02-02 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readdeteil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdeteil',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
