# Generated by Django 2.0 on 2019-02-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190201_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reader_num',
            field=models.IntegerField(default=0),
        ),
    ]
