# Generated by Django 2.0 on 2019-02-02 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_reader_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='reader_num',
        ),
    ]
